### ISSUE TITLE
Mineralogy compatibility

### ISSUE THREAD

**Issue by Blackskyliner** [VapourDrive/GenLoader#2]
Currently it's not possible to replace the oreBiome stone types created by the Mineralogy Mod.
You can replace through the 'minecraft:stone' but not target specific regions generated by Mineralogy, like 'mineralogy:schitis' etc. Because it won't recognize these while generating the ores (Maybe the orgen runs too early?)

Would be really frat to get this feature! :+1:

**Comment by Blackskyliner** [comment]
Okay I debugged the code and narrowed it down. But I guess it seems to be some limitation in the Predicate comparision used within the WeightedWorldGenMinable. The part

``` java
if (worldIn.getBlockState(blockpos).getBlock().isReplaceableOreGen(worldIn, blockpos, this.toReplace))
{
    setBlock(worldIn, rand, blockpos);
}
```

within the generate function is valid and gets called even though the following state is captured by my debugging session:

``` java
worldIn.getBlockState(blockpos) = "mineralogy:schist"
this.toReplace = "mineralogy:andesite"
worldIn.getBlockState(blockpos).getBlock().isReplaceableOreGen(worldIn, blockpos, this.toReplace)) = true
```

So it seems it "selects" the "wrong" mineral to replace. setBlock just selects the weighted ore which should get set at that position so thats not within the bug scope anymore. Any idea why this happens?

**Comment by Blackskyliner** [comment]
https://github.com/cyanobacterium/Minecraft_Mineralogy/blob/master/src/main/java/cyano/mineralogy/blocks/Rock.java

returns always true.... So I guess the check in the oregen is odd... We should really check there if it's THE Block to replace even thoug its replacable by the oregen.

**Comment by ColinGBos** [comment]
Hmm, interesting issue; thanks for bringing this up. I set up the block to replace in the same fashion that the minecraft ore generation is set up. WeightedWorldGenMinable is basically the same as WorldGenMinable with the list of weighted chance blocks.
Forgive me for not following completely, you want to get oresto spawn in specific block types from minerology, and not any of the rest? And is genloader failing to spawn them at all, or is its spawning them anywhere?

**Comment by Blackskyliner** [comment]
I just wanted the Oregen to respect the toReplaceBlock I set.
It just didn't cared. It repleaced through everything it randomly found. It was because Mineralogy implemented their Rock::isReplaceableOreGen as always true, not checking the predicate for at least their own instance of that block. Thats what I do now in the code. It should also help with other mods, thinking that returning true there is an clever choice. Maybe it is idk. But my change should now change the behaviour to correctly respect the set toReplaceBlock setting of the generator definition, made within the json files.

You can test the old behavior by adding mineralogy to your minecraft, then use your oregen to only replace a certain stone from them, just set some ore to generate between 0 and 128 with something like 'mineralogy:chert'. It will spawn just everywhere even in "oreBiomes" as they are somehow called by Mineralogy, where the toReplaceBlock, in my example here 'mineralogy:chert' is not even generated.
